- hosts: webservers
  become: true
  become_user: root
  tasks:
  - name: install httpd package
    package: name=httpd state=present
  - name: start httpd service
    service: name=httpd state=started
  - name: Deploy the html code
    copy: src=index.html dest=/var/www/html
  - name: Restart httpd server
    service: name=httpd state=restarted
